### ISSUE TITLE
Are there any plans to implement `ZGroup` ?

### ISSUE THREAD

**Issue by rakuyoMo** [airbnb/epoxy-ios#108]
I did notice that `ZGroup` is mentioned in the [wiki](https://github.com/airbnb/epoxy-ios/wiki/EpoxyLayoutGroups#constrainable-protocol), are there any plans to implement this feature now?

**Comment by thedrick** [comment]
We don't have any immediate plans to implement ZGroup, though I think it would be quite straightforward to do so. If you are interested in working on it I would be happy to review any PRs

**Comment by thedrick** [comment]
I am going to open up a new issue as an enhancement request and close this.
