### ISSUE TITLE
Release Bump?

### ISSUE THREAD

**Issue by daniapopov** [airbnb/epoxy-ios#111]
Are there plans to make another release? Last one was back in Dec.

**Comment by erichoracek** [comment]
Hi Dania! we've been letting the Epoxy APIs for SwiftUI bridging bake for a bit in our codebase, I think we should be ready to publish a new release quite soon. In the interim you should be able to depend directly on a recent SHA from the `master` branch if you'd like to use some of the new functionality.

**Comment by daniapopov** [comment]
Yep! That is what we have been doing 😃

**Comment by erichoracek** [comment]
To follow up, we just released 0.8.0. Thanks for using Epoxy Dania!
