### ISSUE TITLE
How can I add section decoration items using Epoxy?

### ISSUE THREAD

**Issue by SwiftySam** [airbnb/epoxy-ios#24]
First of all let me start this by saying thanks for finally open sourcing Epoxy for iOS.
I've started playing around with this since yesterday and so far I'm very happy with what it can do.

Now back to the question, I couldn't find anything in the wiki or in the code about decoration items. Is there a straight forward way to add decoration items to sections using Epoxy? And if it's not supported at the moment is there a plan to add this feature?

**Comment by erichoracek** [comment]
Hi Sam, thanks for the kind words. There's not currently an API in Epoxy for decoration views as they don't have the same lifecycle as other view subclasses that are queried from the `UICollectionViewDataSource`. Typically, the `UICollectionViewLayout` handles its own decoration views via its `register(_:forDecorationViewOfKind:)` method, and Epoxy does not interface with the `UICollectionViewLayout` directly. As such you should be able to register your decoration views independently of Epoxy on your layout.
