### ISSUE TITLE
VGroup stretched items when given absolute size in UICollectionViewCompositionalLayout.

### ISSUE THREAD

**Issue by Mononster** [airbnb/epoxy-ios#45]
Hi all! Thanks for the awesome library :) very clean and easy to use.

I had one question when implementing a view using VGroup, so basically when given absolute size for NSCollectionLayoutItem, VGroup is not laying out things from top to bottom based on their intrinsicContentSize, instead it would stretch some items in the group to fill the entire view. Wondering is there anyway I can config this behaviour, so items are rendered from top to bottom based on their content size?

Thank you so much!

**Comment by thedrick** [comment]
@Mononster I am going to close this issue - please let me know if that didn't work and provide a code example so I can look into it.
