### ISSUE TITLE
{V|H}Group not updating when styles of inside items change. (i.e update textColor for a label groupItem in VGroupView)

### ISSUE THREAD

**Issue by Mononster** [airbnb/epoxy-ios#46]
Hi Epoxy team!

I encountered a problem when playing around with the library, so I created some groupItem views inside a VGroupView and when I update the styles of the items inside the VGroupView (i.e. change textColor for a label added in the VGroup), the view will not be updated. However, change the content of the item does triggering view updates (I guess this makes much sense as there are recursive diff operations). Wondering did I miss anything here? How should I trigger VGroup updates when updating the styles of the inside components?

Thank you so much for the help!

**Comment by thedrick** [comment]
hey @Mononster could you attach some code so I can take a look?

**Comment by Mononster** [comment]
Hi @thedrick see the attached code, this is how I created a section with VGroupView and items

<img width="757" alt="Screen Shot 2021-08-29 at 2 55 35 PM" src="https://user-images.githubusercontent.com/10178832/131266575-719edd31-bf1a-47fb-8786-6c9db017cbbb.png">

whenever I change `dataSource.titleViewStyle` (i.e from .primary to .secondary) and called setSections again, the view will not get refreshed. Change content does help (title || subtitle).

**Comment by thedrick** [comment]
ah yes good catch @Mononster this is definitely a bug, let me get a fix up

**Comment by Mononster** [comment]
Awesome! Thanks for help :D
