### ISSUE TITLE
How to combine Epoxy and flexLayout?

### ISSUE THREAD

**Issue by tigerAndBull** [airbnb/epoxy-ios#49]
I want to keep the declarative syntax while adopting FlexLayout. SwiftUI is very unfriendly, the layout is not very customizable, and there are some bugs. 
Can Epoxy do it?

**Comment by erichoracek** [comment]
Hi @tigerAndBull, at Airbnb we create Flexbox style layouts using the https://github.com/airbnb/MagazineLayout `UICollectionViewLayout` combined with Epoxy's `CollectionView`. Please feel free to reopen this issue if this doesn't work for your use case.
