### ISSUE TITLE
BarContainerInsetBehavior not able to set through installer.

### ISSUE THREAD

**Issue by Mononster** [airbnb/epoxy-ios#51]
Hi team! Seems like `BarContainerInsetBehavior` (and other properties) in `TopBarContainer` are not able to set through bar installer? I looked through the code and they are indeed public, are there any plans adding these config in a configuration file or in the installer class?

Thanks!!

**Comment by erichoracek** [comment]
Hi @Mononster , you should be able to set those properties via the `container` property of the bar installer, e.g. `installer.container?.insetBehavior = …`. Let me know if this isn't working for you.

**Comment by erichoracek** [comment]
Going to close this issue, feel free to reopen if this isn't working for you.

**Comment by Mononster** [comment]
It worked! Thanks @erichoracek
