### ISSUE TITLE
just curious how much airbnb app has migrated to Swift ? Is airbnb going to transfer to swift totally in the future?

### ISSUE THREAD

**Issue by mobyIsMe** [airbnb/epoxy-ios#53]
as the title says

**Comment by erichoracek** [comment]
@shepting has posted some stats on our codebase size in a twitter thread [here](https://twitter.com/stevenhepting/status/1309249663589969920)—the Objective-C we have remaining has been slowly decreasing over time, and I don't see any reason why this trend would reverse.
