### ISSUE TITLE
What is the best practice for passing variables between controllers?

### ISSUE THREAD

**Issue by rakuyoMo** [airbnb/epoxy-ios#68]
I have a scenario: 

Page B is a detail page, and its data comes from its parent page which is page A.Also this data can be edited in page A.

According to the example code in `MainViewController`, I don't understand how to implement my requirement?

I also have a problem: how to implement the common proxy pattern in UIKit in expory? I want to set the proxy of page B to page A, how do I write my code?

**Comment by thedrick** [comment]
`Epoxy` is not opinionated on how you share data between screens. In your example, I could imagine having some type of data source object that is injected into both view controllers with something like a subscriber pattern being used to respond to and publish updates. `EpoxyNavigationController` is only responsible for pushing and popping view controllers, but how you share data between those controllers is up to you.

**Comment by rakuyoMo** [comment]
> `Epoxy` is not opinionated on how you share data between screens. In your example, I could imagine having some type of data source object that is injected into both view controllers with something like a subscriber pattern being used to respond to and publish updates. `EpoxyNavigationController` is only responsible for pushing and popping view controllers, but how you share data between those controllers is up to you.

This means I can't pass data or events using things like **delegate** or **block**. The only way I can think of at the moment is to do it through **notifications**, which has poor performance for some pages with complex interactions.

Looking forward to a better way to do this.

Epoxy is a very good library, I have been using it for a while and built some pages, look forward to better performance.

**Comment by erichoracek** [comment]
@rakuyoMo You can certainly use delegates or blocks—you would just pass them to the constructed view controller in the `makeViewController` closure of your `NavigationModel`. For example:

```swift
final class MyNavigationViewController: NavigationController {
  @NavigationModelBuilder 
  private var stack: [NavigationModel] {
    // Root
    NavigationModel.root(…)

    // Delegate detail VC
    NavigationModel(
      dataID: …,
      makeViewController: { [weak self] in
        MyDetailViewController(delegate: self)
      },
      remove: { [weak self] in
        self?.state.showDelegateDetail = false
      })

    // Block detail VC
    NavigationModel(
      dataID: …,
      makeViewController: { [weak self] in
        MyDetailViewController(handleResult: { result in
          self?.state.result = …
        })
      },
      remove: { [weak self] in
        self?.state.showBlock = false
      })
  }
}

extension MyNavigationViewController: MyDetailViewControllerDelegate {
  // Implement delegate methods
}

```

**Comment by rakuyoMo** [comment]
> @rakuyoMo You can certainly use delegates or blocks—you would just pass them to the constructed view controller in the `makeViewController` closure of your `NavigationModel`. For example:
> 
> 
> 
> ```swift
> 
> final class MyNavigationViewController: NavigationController {
> 
>   @NavigationModelBuilder 
> 
>   private var stack: [NavigationModel] {
> 
>     // Root
> 
>     NavigationModel.root(…)
> 
> 
> 
>     // Delegate detail VC
> 
>     if state.showDelegateDetail {
> 
>       NavigationModel(
> 
>         dataID: …,
> 
>         makeViewController: { [weak self] in
> 
>           MyDelegateDetailViewController(delegate: self)
> 
>         },
> 
>         remove: { [weak self] in
> 
>           self?.state.showDelegateDetail = false
> 
>         })
> 
>     }
> 
> 
> 
>     // Block detail VC
> 
>     if state.showBlockDetail {
> 
>       NavigationModel(
> 
>         dataID: …,
> 
>         makeViewController: { [weak self] in
> 
>           MyBlockDetailViewController(handleResult: { result in
> 
>             self?.state.result = …
> 
>           })
> 
>         },
> 
>         remove: { [weak self] in
> 
>           self?.state.showBlockDetail = false
> 
>         })
> 
>     }
> 
>   }
> 
> }
> 
> 
> 
> extension MyNavigationViewController: MyDelegateDetailViewControllerDelegate {
> 
>   // Implement delegate methods
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> In the example project we use blocks/closures to have callbacks from a detail view controller to the navigation controller.

I now understand that for the values necessary to initialize the next control, it can be relayed in the NavigationController via block or delegate.

Thank you very much for your answer and please forgive my stupidity.
