### ISSUE TITLE
How should the child view be horizontally aligned with the parent view?

### ISSUE THREAD

**Issue by rakuyoMo** [airbnb/epoxy-ios#69]
I'm trying to emulate the system's navigation bar using `EpoxyLayoutGroup`.

On the system navigation bar, the title is horizontally centered with respect to the parent view, and the left and right views do not affect its position.

How can I use `EpoxyLayoutGroup` to achieve this feature? Or can I only use `AutoLayout` to achieve it?

**Comment by thedrick** [comment]
I would recommend using an HGroup with the following (pseudocode):

```
HGroup {
  navigationButton
  .contentHuggingPriority(.required, for: .horizontal)
  .compressionResistancePriority(.required, for: .horizontal)
  
  SpacerItem()

  titleLabel
  .textAlignment(.center)

  SpacerItem()

  trailingView
  .contentHuggingPriority(.required, for: .horizontal)
  .compressionResistancePriority(.required, for: .horizontal)
}
```

Let me know if this doesn't work or doesn't make sense. Compression resistance and hugging priorities are pretty important when it comes to Auto Layout and using EpoxyLayoutGroups successfully.
