### ISSUE TITLE
When using EpoxyCollectionView, how to know that the Cell is reused?

### ISSUE THREAD

**Issue by rakuyoMo** [airbnb/epoxy-ios#71]
I am using `RxSwift` and need to cancel the binding operation when the cell is reused.

But `EpoxyableView` is not a `Cell`, so it doesn't have a `prepareForReuse` method.

So how do I know that the view is reused?

**Comment by thedrick** [comment]
There is no callback for when the cell is reused. We believe that views should not contain any owned state, and instead should be dumb renderers that render exactly what is set on them. I haven't used RxSwift before so I'm not sure the best way to integrate it with Epoxy.

**Comment by rakuyoMo** [comment]
> There is no callback for when the cell is reused. We believe that views should not contain any owned state, and instead should be dumb renderers that render exactly what is set on them. I haven't used RxSwift before so I'm not sure the best way to integrate it with Epoxy.

What about adding a `didReused(_:)` callback like the `didSelect(_:)` method?

**Comment by erichoracek** [comment]
Perhaps you could discuss your use case—perhaps there is a more idiomatic "Epoxy" way to accomplish what you're trying to do. Across thousands of screens we haven't yet needed the ability to know when a cell is about to be reused to Tyler's point.

**Comment by rakuyoMo** [comment]
> Perhaps you could discuss your use case—maybe there is a more idiomatic "Epoxy" way to accomplish what you're trying to do. Across thousands of screens we haven't yet needed the ability to know when a cell is about to be reused to Tyler's point.

I am using `Combine` as an example. I have a list where there is a `button` on each `cell`.

I have written an extension for UIControl as follows:

```swift
extension XX where Base: UIControl {
    public func controlEvents(_ event: UIControl.Event) -> UIControlPublisher<Base> {
        return UIControlPublisher<Base>(control: base, event: event)
    }
}
```

A more realistic use case for it is shown below:

```swift
class ARow: UIView, EpoxyableView {
    private lazy var button = UIButton(type: .custom)
    
    private lazy var cancellable = Set<AnyCancellable>()
    
    // ...
    
    func setBehaviors(_ behaviors: Behaviors?) {
        guard let behaviors = behaviors else { return }
        
        button.xx
              .controlEvents(.touchUpInside)
              .sink(receiveValue: behaviors.didClickButton)
              .store(in: &cancellable)
    }
}
```

If I am in a Cell, then I can cancel this subscription in the `prepareForReuse` method to prevent problems with reuse. Something like the following:

```swift
override func prepareForReuse() {
    super.prepareForReuse()
    
    cancellable.forEarch { $0.cancel() }
}
```

**Comment by thedrick** [comment]
`setBehaviors` is set whenever a cell is about to be displayed as well as when cells are reordered in the CollectionView so you should be able to do this without issue:

```swift
class ARow: UIView, EpoxyableView {
    private lazy var button = UIButton(type: .custom)
    
    private lazy var cancellable = Set<AnyCancellable>()
    
    // ...
    
    func setBehaviors(_ behaviors: Behaviors?) {
        cancellable.forEach { $0.cancel() }

        guard let behaviors = behaviors else { return }
        
        button.xx
              .controlEvents(.touchUpInside)
              .sink(receiveValue: behaviors.didClickButton)
              .store(in: &cancellable)
    }
}
```
