### ISSUE TITLE
It is recommended to make `Content` following `Equatable` optional.

### ISSUE THREAD

**Issue by rakuyoMo** [airbnb/epoxy-ios#72]
Suppose I have a more complex `EpoxyableView` that has a Content that needs to be set using multiple values.

Considering the reusability of this view, I want to use an abstract protocol to represent the properties it needs. This would reduce the number of conversions between models and improve performance.

But `Equatable` got in the way when I tried to use a protocol to represent `Content`.

I did notice the following in the [documentation](https://github.com/airbnb/epoxy-ios/wiki/EpoxyCore#contentconfigurableview):

> The `Content` type being `Equatable` is used by `EpoxyCollectionView` to perform performant diffing when setting sections on a `CollectionView`.

I prefer to use a more comfortable way of writing my programs than the performance gains that `Equatable` brings. When I need more extreme performance, I will consider following the `Equatable` protocol, but do not want to add `Equatable` to every model.

So I'd like `Content` to stop requiring `Equatable` to be implemented.

Maybe using `as?` at the call would be a good way to go?

**Comment by thedrick** [comment]
All of our `Content` types must be equatable for Epoxy to be able to create diffs between lists of items and sections. Without the Equatable requirement, Epoxy would not know if items were deleted, added, or moved, and it would need to hard refresh everything whenever the sections are set.

One way to make your `Equatable` conformance easier to do is use something like [Sourcery](https://github.com/krzysztofzablocki/Sourcery) to generate `Equatable` conformances for all of your `Content` types. You can also have your `Content` models be `structs` and `Equatable` will be generated automatically for you by the compiler as long as all of the properties of that struct are also `Equatable`.

**Comment by rakuyoMo** [comment]
> All of our `Content` types must be equatable for Epoxy to be able to create diffs between lists of items and sections. Without the Equatable requirement, Epoxy would not know if items were deleted, added, or moved, and it would need to hard refresh everything whenever the sections are set.
> 
> One way to make your `Equatable` conformance easier to do is use something like [Sourcery](https://github.com/krzysztofzablocki/Sourcery) to generate `Equatable` conformances for all of your `Content` types. You can also have your `Content` models be `structs` and `Equatable` will be generated automatically for you by the compiler as long as all of the properties of that struct are also `Equatable`.

I can understand the huge performance improvement of having `Content` follow `Equalable`, but I don't think it's conducive to reusing `EpoxyableView` views unless I use a tool like `Sourcery` to help me generate a lot of duplicate model code 

—— the network model and the view model are almost identical, and I need to regenerate the template code after one change. are almost identical, and I need to regenerate the model code after a change, which can be devastating if someone forgets to perform some action. At this point I have to take some other extra steps to avoid these things from happening 

—— maybe I should have spent some extra time to write these models twice or more in the first place.

Well the above are just some of my self-talking complaints, and I look forward to Apple making my ideas possible so that I can get more performance while also making my code more concise without resorting to other third-party tools.
