### ISSUE TITLE
iOS 9 supporting issues

### ISSUE THREAD

**Issue by kangwang1988** [airbnb/epoxy-ios#85]
Hi, it seems epoxy-iOS require the target os version of iOS 13+, is it possible to run epoxy in legacy os like iOS9+?

**Comment by thedrick** [comment]
It is currently not possible to build Epoxy to target an OS as old as iOS 9 and is not something that would warrant the effort to support. Looking at [Apple's own statistics](https://developer.apple.com/support/app-store/) shows that supporting something older than 13 would only be a small percentage of users and devices.

If you need Epoxy to support iOS 9, I would encourage you to fork the project. Once you do that and update the minimum target version, you will encounter errors where the APIs are newer than iOS 9 and will need to provide workarounds or delete those features.
